services:
  - type: web
    name: express-app
    runtime: node
    repo: https://github.com/Rey5440/Top-Tech-Back
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
  - type: redis
    name: redis-db
    ipAllowList:
      - source: 0.0.0.0/0
        description: Permitir conexiones desde cualquier lugar
databases:
  - name: mongodb
    databaseName: mydb
    user: myuser
    ipAllowList:
      - source: 0.0.0.0/0
        description: Permitir conexiones desde cualquier lugar